// <auto-generated />
namespace EHotelServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EHotelDB_v5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EHotelDB_v5));
        
        string IMigrationMetadata.Id
        {
            get { return "202105231452237_EHotelDB_v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
