//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHotelServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImageDbModels : DbContext
    {
        public ImageDbModels()
            : base("name=ImageDbModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Image { get; set; }

        public System.Data.Entity.DbSet<EHotelServices.Models.Usluga> Uslugas { get; set; }

        public System.Data.Entity.DbSet<EHotelServices.Models.Osoblje> Osobljes { get; set; }
    }
}
